language: node_js
node_js:
  - 12

cache: npm

before_script:
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

script:
  - npm run lint
  - npm test

after_success:
  - npm run coverage
  - cat coverage/lcov.info | coveralls
