version: "3.9"  # optional since v1.27.0
services:
  contracts:
    build: .
    ports:
      - "8545:8545"
    volumes:
      - type: bind
        source: ./deployed
        target: /usr/src/app/deployed